# Generated by Django 2.1.4 on 2019-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190406_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dueDate',
            field=models.CharField(default='Not issued yet.', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='issueDate',
            field=models.CharField(default='Not issued yet.', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='Book not available for purchase.', max_length=10),
        ),
    ]
